### ISSUE TITLE
The integration with AVO did not work as expected

### ISSUE THREAD

**Issue by iyolee** [PostHog/posthog-avo-plugin#5]
Hello, when I use this plugin to integrate with AVO and report events using `posthog.capture`, composeWebhook metrics should update, but AVO does not receive the event trigger.

## Reproduction Steps

1. Configure Inspector Events for AVO
2. Enable the Avo Inspector Plugin in the Data pipeline-Apps in PostHog and configure the Avo API Key
3. Use `posthog.capture` to report events to posthog
    ``` ts
    posthog.capture('event-test-by-posthog', {
			property1: 'value',
			property2: 'another value',
		});
   ```

## Actual Results
posthog receives the reported event and the avo plugin has the corresponding composeWebhook metrics statistics:

<img width="1302" alt="image" src="https://github.com/PostHog/posthog-avo-plugin/assets/22022721/3cfc60c0-36fa-41ee-bc18-6d3ca62d3471">

<img width="1334" alt="image" src="https://github.com/PostHog/posthog-avo-plugin/assets/22022721/a41a5f3f-b188-41a4-b41a-d289b5b535a2">

**However, AVO did not receive the corresponding event trigger:**

<img width="961" alt="image" src="https://github.com/PostHog/posthog-avo-plugin/assets/22022721/cdc0479c-e9b2-4a33-aaba-2e68f4f20ea7">

## Expected

The avo can receive the corresponding event trigger.

## Supplementary Statement

Calling the api interface `https://api.avo.app/inspector/posthog/v1/track` can trigger AVO events.

**Comment by tomasfarias** [comment]
Hello @iyolee!

Thank you for reporting this issue.

After some testing, we realized PostHog is double dumping the JSON body sent to Avo, which is causing Avo to reject or not process the event. It was hard to spot the issue as the Avo API doesn't return an error (always replies with 200 OK), so we had to do a lot of trials to find the error.

Anyways, we will be pushing out a patch to address the issue today and the issue should be resolved by updating the Avo app after the patch is released (we will do that ourselves for PostHog cloud).

**Comment by tiina303** [comment]
https://github.com/PostHog/posthog/pull/19873

**Comment by tomasfarias** [comment]
Actually, we will fix this issue over at https://github.com/PostHog/posthog (https://github.com/PostHog/posthog/pull/19873). So PostHog will have to be updated to address this issue (again, we will do this in PostHog Cloud, but self-hosted users have to pull the latest changes).

**Comment by tomasfarias** [comment]
PRs merged, this should be fixed in latest PostHog.
